source "https://rubygems.org"
gem "jekyll"
# jekyll alone might be enough for most use-cases
gem "jekyll-avatar"
gem "jekyll-mentions", ">= 1.6.0"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jemoji", ">= 0.12.0"
