source "https://rubygems.org"
gem "jekyll", ">= 4.1.1"
# jekyll alone might be enough for most use-cases
gem "jekyll-avatar", ">= 0.7.0"
gem "jekyll-mentions", ">= 1.6.0"
gem "jekyll-seo-tag", ">= 2.6.1"
gem "jekyll-sitemap", ">= 1.4.0"
gem "jemoji", ">= 0.12.0"
