source 'https://rubygems.org'

if ENV['CUSTOM_RUBY_VERSION']
  ruby ENV['CUSTOM_RUBY_VERSION'] # i.e.: '2.3'
end

gem 'rails', '~> 5.2', '>= 5.2.4.4'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2.2'

gem 'mysql2', group: :mysql
gem 'pg', group: :postgresql
gem 'sqlite3', group: :sqlite3

# Use Puma as the app server
gem 'puma', '>= 5.3.1'

# Capistrano for deployment
group :capistrano do
  gem 'airbrussh'
  gem 'capistrano', '~> 3.4.1', require: false
  gem 'capistrano-rails', '>= 1.1.8', require: false
  gem 'capistrano-bundler', '>= 1.1.4', require: false
  gem 'capistrano-rvm', '>= 0.1.2', require: false
  gem 'capistrano3-puma', '>= 1.2.1', require: false
end

# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 4.4.0'
gem 'jquery-migrate-rails'
gem 'jquery-ui-rails', '>= 6.0.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.6', '>= 2.6.4'

gem 'activeresource', '>= 5.1.1'
gem 'acts_as_commentable'
gem 'bcrypt'
gem 'cancancan'
gem 'cocoon'
gem 'dotenv-rails', '>= 2.2.2'
gem 'haml', '>= 5.0.0'
gem 'localized_language_select', github: 'frab/localized_language_select', branch: 'master'
gem 'nokogiri', '>= 1.10.8'
gem 'paperclip', '~> 5.2', '>= 5.2.1'
gem 'paper_trail', '>= 5.2.2'
gem 'prawn', '< 1.0'
gem 'prawn_rails', '>= 0.0.11'
gem 'ransack', '>= 1.8.2'
gem 'ri_cal'
gem 'roust', '>= 1.8.9'
gem 'rqrcode'
#gem 'roust', :git => 'git@github.com:bulletproofnetworks/roust.git'
gem 'simple_form', '>= 5.0.0'
gem 'sucker_punch'
gem 'transitions', require: ['transitions', 'active_record/transitions']
gem 'will_paginate'

group :production do
  gem 'exception_notification', '>= 4.2.1'
end

group :development, :test do
  gem 'bullet', '>= 5.4.0'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'letter_opener'
  gem 'faker', '>= 1.6.6'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails', '~> 4.7', '>= 4.7.0'
  gem 'shoulda', '>= 3.5.0'
end

group :doc do
  gem 'redcarpet'       # documentation
  gem 'github-markdown' # documentation
  gem 'yard'            , '>= 0.9.20' # documentation
  # gem 'rails-erd'      # graph
  # gem 'ruby-graphviz', require: 'graphviz' # Optional: only required for graphing
end
