source "https://rubygems.org"

gem "jekyll", ">= 4.1.1"

gem "jekyll-avatar", ">= 0.7.0"
gem "jekyll-mentions", ">= 1.6.0"
gem "jekyll-seo-tag", ">= 2.6.1"
gem "jekyll-sitemap", ">= 1.4.0"
gem "jemoji", ">= 0.12.0"

# Optional dependencies:
gem "jekyll-coffeescript"
#gem "jekyll-docs"
gem "jekyll-feed", "~> 0.15", ">= 0.15.0"
gem "jekyll-gist", ">= 1.5.0"
gem "jekyll-paginate"
gem "jekyll-redirect-from", ">= 0.16.0"
gem "kramdown-syntax-coderay"
gem "mime-types", "~> 3.0"
gem "rdoc", "~> 6.0"
gem "tomlrb", "~> 1.2"

platform :ruby, :mswin, :mingw, :x64_mingw do
  gem "classifier-reborn", "~> 2.2"
  gem "liquid-c", "~> 4.0"
  gem "yajl-ruby", "~> 1.4"
end
